base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
	path('posts/', views.posts, name="posts"),
	path('post/<slug:slug>/', views.post, name="post"),
	path('profile/', views.profile, name="profile"),

	# CRUD PATHS

	path('create_post/', views.createPost, name='create_post'),
	path('update_post/<slug:slug>/', views.updatePost, name='update_post'),
	path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),

	path('send_email/', views.sendEmail, name='send_email'),
]

nathanieladiah/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.
class Tag(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Post(models.Model):
	headline = models.CharField(max_length=200)
	sub_headline = models.CharField(max_length=200, null=True, blank=True)
	thumbnail = models.URLField(blank=True, null=True, default="https://i.imgur.com/rCtiN2c.png")
	body = RichTextField(null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=False)
	featured = models.BooleanField(default=False)
	tags = models.ManyToManyField(Tag, null=True)
	slug = models.SlugField(null=True, blank=True)

	def __str__(self):
		return self.headline

	def save(self, *args, **kwargs):

		if self.slug == None:
			slug = slugify(self.headline)

			has_slug = Post.objects.filter(slug=slug).exists()
			count = 1
			while has_slug:
				count += 1
				slug = slugify(self.headline) + '-' + str(count)
				has_slug = Post.objects.filter(slug=slug).exists()

			self.slug = slug

		super().save(*args, **kwargs)

base/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post

class PostForm(ModelForm):

	class Meta:
		model = Post
		fields = '__all__'

		widgets = {
			'tags':forms.CheckboxSelectMultiple(),
		}

base/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from .forms import PostForm
from .models import Post
from .filters import PostFilter

# Create your views here.

def home(request):
	posts = Post.objects.filter(active=True, featured=True).order_by('-created')[0:3]

	context = {'posts': posts}
	return render(request, 'base/index.html', context)

def posts(request):
	# posts = Post.objects.all()
	posts = Post.objects.filter(active=True).order_by('-created')
	myFilter = PostFilter(request.GET, queryset=posts)
	posts = myFilter.qs

	page = request.GET.get('page')

	paginator = Paginator(posts, 6)

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	context = {'posts': posts, 'myFilter': myFilter}
	return render(request, 'base/posts.html', context)

def post(request, slug):
	post = Post.objects.get(slug=slug)
	context = {'post': post}
	return render(request, 'base/post.html', context)

def profile(request):
	return render(request, 'base/profile.html')

# CRUD VIEWS

@login_required(login_url="home")
def createPost(request):
	form = PostForm()

	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid:
			form.save()

			return redirect('posts')

	context = {'form': form}
	return render(request, 'base/post_form.html', context)

@login_required(login_url="home")
def updatePost(request, slug):
	post = Post.objects.get(slug=slug)
	form = PostForm(instance=post)

	if request.method == 'POST':
		form = PostForm(request.POST, instance=post)
		if form.is_valid:
			form.save()

			return redirect('posts')

	context = {'form': form}
	return render(request, 'base/post_form.html', context)

@login_required(login_url="home")
def deletePost(request, slug):
	post = Post.objects.get(slug=slug)

	if request.method == 'POST':
		post.delete()
		return redirect('posts')

	context = {'item': post}
	return render(request, 'base/delete.html', context)

def sendEmail(request):

	if request.method == 'POST':

		template = render_to_string('base/email_template.html', {
			'name':request.POST['name'],
			'email':request.POST['email'],
			'message':request.POST['message'],
		})

		email = EmailMessage(
			request.POST['subject'],
			template,
			settings.EMAIL_HOST_USER,
			[settings.EMAIL_HOST_USER]
			)

		email.fail_silently=False
		email.send()

	return render(request, 'base/email_sent.html')

base/templates/base/delete.html
{%extends 'base/main.html' %}
{% load static %}

{% block content %}

<section class="s2 delete-page">
	<div class="main-container">
		<form method="post" action="">
			{% csrf_token %}
			<p>Are you sure you want to delete {{item}}</p>
			<input class="btn btn-danger" type="submit" value="Confirm">
		</form>
	</div>
</section>

{% endblock content %}

base/templates/base/email_sent.html
{% extends 'base/main.html' %}

{% block content %}

	<!-- <style type="text/css">
		html, body {
			height: 100%;
		}
		#page-wrapper {
			height: 100%;
			display: flex;
			justify-content: center;
			align-items: center;
			text-align: center;
			background-color: #eaeaea;
		}
		
		#success-box {
			max-width: 800px;
			height: auto;
			background-color: #fff;
			border: 1px solid #888;
			border-radius: 5px;
			padding: 15px;
		}

		#success-box  p {
			font-size: 18px;
		}
	</style> -->

	<div id="page-wrapper">
		<div id="success-box" class="content-block">
			<h1>Thanks for reaching out!</h1>
			<p>Your message was successfully sent. I will do my best to get
				back to you in a timely manner :)
			</p> 
			<a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
		</div>
	</div>
{% endblock %}

base/templates/base/email_template.html
{{ message }}

{{ name }}

{{ email }}

base/templates/base/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Nathaniel Adiah</title>

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'base/css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>

<body>

	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm Nathaniel Adiah</h1>
			</div>

			<div class="intro-wrapper">
				
				{% include 'base/navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'base/images/baby.jpg' %}">
					<h5 style="text-align: center; line-height: 0;">Personalize Theme</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Theme settings will be saved for<br> your next visit</p>
				</div>

				<div class="right-column">
					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>What I Do</h3>
							<p>
								Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, impedit!
							</p>
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<div class="about-wrapper">
				<div class="about-me">
					<h4>More about me</h4>
					<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam delectus nemo, eligendi voluptatum accusamus eum alias saepe eos molestiae odit deleniti, facere sint et repellat.</p>
					<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum voluptas neque cupiditate quibusdam, alias ea!</p>

					<hr>
					<h4>TOP EXPERTISE</h4>

					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores officia culpa praesentium!
						<a href="{% static 'base/Resume.pdf' %}" target="_blank">Download Resume</a>
					</p>

					<div id="skills">
						<ul>
							<li>Python</li>
							<li>Django</li>
							<li>JavaScript</li>
							<li>React</li>
							<li>Postgres</li>
						</ul>
						<ul>
							<li>Python</li>
							<li>Django</li>
							<li>JavaScript</li>
							<li>React</li>
							<li>Postgres</li>
						</ul>
					</div>
				</div>

				<div class="social-links">
					<img id="social_img" src="{% static 'base/images/beach.jpg' %}">
					<h3>Find me on Twitter & the Rest</h3>
					<a target="_blank" href="#">facebook: @Nathaniel Adiah</a>
					<br>
					<a target="_blank" href="https://twitter.com/NathanielAdiah">Twitter: @NathanielAdiah</a>
				</div>
			</div>
		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">Some of my past projects</h3>

			<div class="post-wrapper">
				{% for post in posts %}
				<div>
					<div class="post">
						<img class="thumbnail" src="{{post.thumbnail}}">
						<div class="post-preview">
							<h6 class="post-title">{{ post.headline }}</h6>
							<p class="post-intro">{{ post.sub_headline }}</p>
							<a href="{% url 'post' post.slug %}">Read More</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>

			<p align="center">
				<a href="{% url 'posts' %}">View More</a>
			</p>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="post" action="{% url 'send_email' %}">
				{% csrf_token %}
				<label>Name</label>
				<input class="input-field" type="text" name="name">

				<label>Subject</label>
				<input class="input-field" type="text" name="subject">

				<label>Email</label>
				<input class="input-field" type="email" name="email">

				<label>Message</label>
				<textarea class="input-field" name="message"></textarea>

				<input id="submit-btn" type="submit" value="Send">
			</form>
		</div>
	</section>

	<script type="text/javascript">
		let static = "{% static 'base/css' %}"
	</script>
	
	<script type="text/javascript" src="{% static 'base/js/script.js' %}"></script>
</body>
</html>

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Nathaniel Adiah</title>

	<!-- <link
	href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
	rel="stylesheet"
	integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
	crossorigin="anonymous"> -->

	<link 
	rel="stylesheet" 
	href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" 
	integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" 
	crossorigin="anonymous">

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'base/css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>

	{% include 'base/navbar.html' %}

	{% block content %}
	<!-- Content goes here -->
	{% endblock content %}

	 <!-- Bootstrap script -->
	<!-- <script
	src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
	integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
	crossorigin="anonymous"></script> -->

	<script type="text/javascript">
		let static = "{% static 'base/css' %}"
	</script>
	
	<script type="text/javascript" src="{% static 'base/js/script.js' %}"></script>	

	<script 
	src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" 
	integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
	crossorigin="anonymous"></script>
	<script 
	src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" 
	integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" 
	crossorigin="anonymous"></script>
	
</body>
</html>

base/templates/base/navbar.html
<div class="nav-wrapper">
	<a href="{% url 'home' %}">
		<div class="dots-wrapper">
			<div id="dot-1" class="browser-dot">
			</div>
			<div id="dot-2" class="browser-dot">
			</div>
			<div id="dot-3" class="browser-dot">
			</div>
		</div>
	</a>

	<ul id="navigation">
		<li><a href="{% url 'home' %}">Home</a></li>
		<!-- <li><a href="#">Contact</a></li>
		<li><a href="#">Contact</a></li> -->
		{% if request.user.is_authenticated %}
			<li><a href="{% url 'create_post' %}">Create Post</a></li>
		{% endif %}
	</ul>
</div>

base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<!-- <style type="text/css">
	img{
		max-width: 100%;
		object-fit: cover;
	}

	.featured_image{
		margin-top: 20px;
		margin-bottom: 20px;
		width: 100%;
	}

	.post-container{
			width: 900px;
			margin: 0 auto;
			padding-top: 20px;
			padding-bottom: 20px;
	}

	.comments-wrapper{
		margin-top: 50px;
		padding: 10px;
		border:1px solid var(--borderColor);
		-webkit-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		-moz-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
	}

	.comment{
		display: flex;
		padding: 15px;
	}

	.comment-author{
		font-size: 14px;
		font-weight: 700;
		color: rgb(30, 174, 219) !important;
		margin: 2px;
	}

	.author-pic{
		width: 50px;
		height: 50px;
		border-radius: 50%;
		margin-right: 10px;
	}

	.comment-body{

		font-size: 14px;
	}

	@media screen and (max-width: 900px){
		.post-container{
			width: 95%;
		}
	}
</style> -->

<section class="s2 post-page">

	<div class="main-container">
		<a class="btn btn-sm btn-primary mt-3" href="{% url 'posts' %}">&laquo Back to Posts</a>


		<img class="featured_image" src="{{ post.thumbnail }}">

		{% for tag in post.tags.all %}
			<span class="tag">{{ tag }}</span>
		{% endfor %}

		<h1>{{ post.headline }}</h1>
		<h4>{{ post.sub_headline }}</h4>
		<br>

		<p>
			{{ post.body|safe }}
		</p>
	</div>
</section>	

{% endblock content %}

base/templates/base/post_form.html
{% extends 'base/main.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<!-- <style type="text/css">
	#div_id_tags > div {
		max-height: 100px;
		overflow-y: scroll;
		border: 1px solid #888;
		padding: 5px;
		border-radius: 5px;
	}

	.django-ckeditor-widget {
	width: 100%;
	}
</style> -->
<section class="s2">
	<div class="main-container">
		<h3 class="mt-3">Post Form</h3>

		<form action="" method="post">
			{% csrf_token %}
			{{ form.media }}
			{{ form|crispy }}

			<input class="my-3 btn btn-primary" type="submit" value="Submit Post">

		</form>
	</div>
</section>
{% endblock content %}

base/templates/base/posts.html
{% extends 'base/main.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!-- <style type="text/css">
	#id_tags {
		overflow-y: scroll;
		max-height: 100px;
		border-radius: 5px;
		padding: 5px;
	}
</style> -->
<section class="s2">
	<div class="main-container">
		<h1>Posts</h1>

		<form class="mb-3" id="searchForm" method="get">
			{{ myFilter.form|crispy }}
			<input class="btn btn-primary" type="submit" value="search">
		</form>

		<div class="post-wrapper">

			{% for post in posts %}
			<div>
				<div class="post">
					<img class="thumbnail" src="{{ post.thumbnail }}">
					<div class="post-preview">
						<h6 class="post-title">{{ post.headline }}</h6>
						<p class="post-intro">{{ post.sub_headline }}</p>
						<a href="{% url 'post' post.slug %}">Read More</a>

						{% if request.user.is_authenticated %}
							| <a href="{% url 'update_post' post.slug %}">Edit</a>
							| <a href="{% url 'delete_post' post.slug %}">Delete</a>
						{% endif %}

						<hr>
						{% for tag in post.tags.all %}
							<span class="tag">{{ tag }}</span>
						{% endfor %}

					</div>
				</div>
			</div>
			{% empty %}
				<h3>No posts found...</h3>
			{% endfor %}

		</div>

		<div class="row">
			{% if posts.has_other_pages %}
				<ul class="pagination">

					{% if posts.has_previous %}
						<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{ posts.previous_page_number}}" class="page-link">
							&laquo</a></li>

						<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
					{% endif %}

					{% for i in posts.paginator.page_range %}
						{% if posts.number == i %}
							<li class="page-item"><a class="active page-link">{{ i }}</a></li>
						{% else %}
							<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{ i }}</a></li>
						{% endif %}
					{% endfor %}

					{% if posts.has_next %}
						<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

						<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{ posts.next_page_number}}" class="page-link">
							&raquo</a></li>

					{% endif %}	
				</ul>
			{% endif %}
		</div>
	</div>
</section>

<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	// try a foreach here instead
	for(var i=0; pageLinks.length > i; i++){
		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden>`
			searchForm.submit()
		})
	}
</script>

{% endblock content %}

base/templates/base/profile.html
{% extends 'base/main.html' %}

{% block content %}

<h1>User Profile</h1>

{% endblock content %}